language: python
sudo: false
addons:
  postgresql: "9.3"
  apt:
    packages:
    - libopenjpeg-dev
    - libpng-dev
    - libgrib-api-dev
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -U postgres -c "CREATE DATABASE athena;"
  - psql -U postgres -c "CREATE EXTENSION postgis" -d athena
  - psql -U postgres -c "CREATE USER athena WITH SUPERUSER PASSWORD 'pass';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE athena TO athena;"
script:
  - "python manage.py test"
after_success:
  coveralls
