postgres:
  restart: always
  image: mdillon/postgis:9.4
  ports:
    - "5432"

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379"

app:
  restart: always
  build: ./app
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./app:/code
  environment:
    - DJANGO_SETTINGS_MODULE=athena.settings
  command: python /code/manage.py runserver 0.0.0.0:8000

worker:
  restart: always
  build: ./app
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./app:/code
  environment:
    - DJANGO_SETTINGS_MODULE=athena.settings
  command: celery -A athena worker -l info

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  links:
    - app:app
